//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectColectiv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arhiva
    {
        public int id_Arhiva { get; set; }
        public string Internari { get; set; }
        public string Alergii { get; set; }
        public string Boli { get; set; }
        public string Retete { get; set; }
        public string Vaccinuri { get; set; }
        public string Diagnosticuri { get; set; }
    
        public virtual FisaMedicala FisaMedicala { get; set; }
    }
}
