//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectColectiv
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatePersonale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatePersonale()
        {
            this.Utilizator = new HashSet<Utilizator>();
        }
    
        public int id_DatePersonale { get; set; }
        public string CNP { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> Varsta { get; set; }
        public string Sex { get; set; }
        public string Adresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utilizator> Utilizator { get; set; }
    }
}
