//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectColectiv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istoric
    {
        public int id_Istoric { get; set; }
        public string TipObiect { get; set; }
        public Nullable<int> IdObiect { get; set; }
        public Nullable<System.DateTime> DataModificarii { get; set; }
        public string ValoareVeche { get; set; }
        public string ValoareNoua { get; set; }
    }
}
