//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectColectiv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamente
    {
        public int id_Medicament { get; set; }
        public string Nume { get; set; }
        public Nullable<int> Cantitate { get; set; }
        public string Administrare { get; set; }
    
        public virtual Retete Retete { get; set; }
    }
}
