//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectColectiv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programari()
        {
            this.Diagnostic = new HashSet<Diagnostic>();
        }
    
        public int id_Programare { get; set; }
        public Nullable<System.DateTime> DataOraEfectuare { get; set; }
        public string StatusProgramare { get; set; }
        public Nullable<System.DateTime> DataConsultatiei { get; set; }
        public Nullable<System.DateTime> DataModificarii { get; set; }
    
        public virtual Asistent Asistent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnostic> Diagnostic { get; set; }
        public virtual Medic Medic { get; set; }
        public virtual Pacient Pacient { get; set; }
    }
}
