//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectColectiv
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProiectColectivEntities : DbContext
    {
        public ProiectColectivEntities()
            : base("name=ProiectColectivEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<Alergii> Alergii { get; set; }
        public virtual DbSet<Arhiva> Arhiva { get; set; }
        public virtual DbSet<Asistent> Asistent { get; set; }
        public virtual DbSet<Boli> Boli { get; set; }
        public virtual DbSet<DatePersonale> DatePersonale { get; set; }
        public virtual DbSet<Diagnostic> Diagnostic { get; set; }
        public virtual DbSet<FisaMedicala> FisaMedicala { get; set; }
        public virtual DbSet<Internari> Internari { get; set; }
        public virtual DbSet<Istoric> Istoric { get; set; }
        public virtual DbSet<Medic> Medic { get; set; }
        public virtual DbSet<Medicamente> Medicamente { get; set; }
        public virtual DbSet<Pacient> Pacient { get; set; }
        public virtual DbSet<Programari> Programari { get; set; }
        public virtual DbSet<Retete> Retete { get; set; }
        public virtual DbSet<Utilizator> Utilizator { get; set; }
        public virtual DbSet<Vaccinuri> Vaccinuri { get; set; }
    }
}
